version: "3.9"

networks:
  web_network:
    name: laravel9
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel9-app
    container_name: laravel9_app
    restart: always
    volumes:
      - ./src:/var/www
    networks:
      - web_network

      # MySQL Database
  db:
    image: mysql
    container_name: laravel9_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=laravel9db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    ports:
      - "3308:3306"
    restart: always
    networks:
      - web_network
      #Nginx Web Server Service
  nginx:
    image: nginx:latest
    container_name: laravel9_nginx
    volumes:
      - ./src:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    ports:
      - "8100:80"
    restart: always
    networks:
      - web_network
      # Redis it same local storage
  redis:
    image: redis:6.2.1-buster
    container_name: laravel9_redis
    volumes:
      - ./redis/data:/data
    restart: always
    networks:
      - web_network

      # mailhog (test send mail local)
  mailhog:
    image: mailhog/mailhog
    container_name: laravel9_mailhog
    ports:
      - 8025:8025
    restart: always
    tty: true
    networks:
      - web_network
      # phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    container_name: laravel9_phpmyadmin
    environment:
      - PMA_HOST:db
      - PMA_PORT:3306
      - PMA_USER:admin
      - PMA_PASSWORD:1234
    ports:
      - 8080:80
    restart: always
    networks:
      - web_network
